const CID_COOKIE_NAME = "LP_CID";
const AID_COOKIE_NAME = "LP_AID";

const PERSONALIZATION_ATTRIBUTE = "data-lp-var";
const PERSONALIZATION_ATTRIBUTE_COPY = "data-lp-var-copy";
const PERSONALIZATION_ATTRIBUTE_SRC = "data-lp-var-src";
const PERSONALIZATION_ATTRIBUTE_HREF = "data-lp-var-href";
const CUSTOM_PERSONALIZATION_ATTRIBUTES = [
  PERSONALIZATION_ATTRIBUTE_COPY,
  PERSONALIZATION_ATTRIBUTE_SRC,
  PERSONALIZATION_ATTRIBUTE_HREF,
];
const ALL_PERSONALIZATION_ATTRIBUTES = [
  PERSONALIZATION_ATTRIBUTE,
  ...CUSTOM_PERSONALIZATION_ATTRIBUTES,
];
const PERSONALIZATION_FLAG = "data-lp-var-ready";

export {
  CID_COOKIE_NAME,
  AID_COOKIE_NAME,
  PERSONALIZATION_ATTRIBUTE,
  PERSONALIZATION_ATTRIBUTE_COPY,
  PERSONALIZATION_ATTRIBUTE_SRC,
  PERSONALIZATION_ATTRIBUTE_HREF,
  CUSTOM_PERSONALIZATION_ATTRIBUTES,
  ALL_PERSONALIZATION_ATTRIBUTES,
  PERSONALIZATION_FLAG,
};
